<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputPath>../bin</OutputPath>
    <TargetFramework>net10.0</TargetFramework>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>exceltk</RootNamespace>
    <AssemblyName>exceltk</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>table.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeIdentifiers>win-x86;osx-x64;osx-arm64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="table.ico" />
  </ItemGroup>

</Project>
